import { useState } from 'react'
import { Check, Download, FileText, ShieldCheck } from 'lucide-react'
import AppShell from '../components/AppShell'

const plans=[['Start','4 900','1 об’єкт',['5 офісних користувачів','50 ГБ доказів','Базові пакети']],['Control','10 900','3 об’єкти',['15 офісних користувачів','200 ГБ доказів','Варіації та зовнішній review']],['Portfolio','22 000+','8+ об’єктів',['API та webhooks','Власні шаблони','Пріоритетний супровід']]]
export default function Billing(){
  const [selected,setSelected]=useState('Control'); const [saved,setSaved]=useState(false); const [downloadedInvoice,setDownloadedInvoice]=useState(null)
  return <AppShell title="Тариф і рахунки" eyebrow="ЕнергоПро Монтаж"><div className="page-content billing-page"><section className="current-plan"><div><span>ПОТОЧНИЙ ТАРИФ</span><h2>Control</h2><p>3 з 3 активних об’єктів · 11 з 15 офісних користувачів</p></div><div><strong>10 900 ₴</strong><span>на місяць · без ПДВ</span><small>Наступний рахунок 01.08.2026</small></div></section><section><div className="section-line"><div><h2>Оберіть масштаб</h2><p>Польові користувачі включені без доплати.</p></div><div className="billing-note"><ShieldCheck size={18}/> Дані не видаляються при зміні тарифу</div></div><div className="billing-plans">{plans.map(([name,price,capacity,features])=><button key={name} onClick={()=>{setSelected(name);setSaved(false)}} aria-pressed={selected===name} className={selected===name?'selected':''}><span className="radio"><i/></span><div><h3>{name}</h3><b>{capacity}</b><ul>{features.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul></div><strong>{price}<small>₴ / міс.</small></strong></button>)}</div><div className="plan-action" aria-live="polite"><div><b>{selected=== 'Control'?'Ваш поточний тариф':`Перейти на ${selected}`}</b><span>{selected==='Portfolio'?'Ми підготуємо пропозицію після короткої розмови.':selected==='Start'?'Зміна набуде чинності з наступного періоду.':'Жодних змін до наступного рахунку.'}</span></div><button disabled={selected==='Control'||saved} onClick={()=>setSaved(true)} className="button button--dark">{saved?'Запит надіслано':'Підтвердити зміну'}</button></div></section><section className="invoices"><div className="section-line"><div><h2>Історія рахунків</h2><p>Оплата за безготівковим рахунком.</p></div></div>{downloadedInvoice && <div className="toolbar-receipt" role="status">{downloadedInvoice} · PDF підготовлено (demo)</div>}{[['AF-2026-071','01.07.2026','10 900 ₴','Оплачено'],['AF-2026-061','01.06.2026','10 900 ₴','Оплачено']].map(row=><div className="invoice-row" key={row[0]}><FileText size={19}/><b>{row[0]}</b><span>{row[1]}</span><strong>{row[2]}</strong><span className="paid-dot">{row[3]}</span><button className="icon-button" aria-label={`Завантажити рахунок ${row[0]}`} onClick={()=>setDownloadedInvoice(row[0])}><Download size={17}/></button></div>)}</section></div></AppShell>
}
