import { useState } from 'react'
import { AlertTriangle, ArrowRight, Check, FileCheck2, LockKeyhole, RotateCcw, ShieldCheck } from 'lucide-react'
import Brand from '../components/Brand'

export default function ExternalReview() {
  const [step, setStep] = useState(0)
  const [decision, setDecision] = useState(null)
  const [section, setSection] = useState('Огляд пакета')
  const sections = ['Огляд пакета', 'Обсяги робіт', 'Індекс доказів', 'Waivers', 'Історія версій']
  const sectionCopy = {
    'Огляд пакета': ['Що саме підтверджується', ['EL-04.17 · Кабель ВВГнг · 648 м', 'EL-07.02 · Кабельні лотки · 312 м', 'EL-14.01 · Протокол вимірювання']],
    'Обсяги робіт': ['Обсяги, включені у v2', ['428 позицій · snapshot CTR-2026-02 v3', 'Виконано 3 400 000 ₴', 'Включено до подання 2 650 000 ₴']],
    'Індекс доказів': ['84 оригінали з перевіреним походженням', ['CAP-742 · 2 фото · hash 6f2a…91c0', 'DOC-184 · Акт прихованих робіт · v2', 'TST-041 · Протокол вимірювання']],
    Waivers: ['1 розкритий waiver', ['EL-11.08 · Виконавча схема', 'Чинний до 31.07.2026', 'Власник: Ірина Коваленко · ВТВ']],
    'Історія версій': ['Незмінний ланцюг пакета', ['v1 · 21.07.2026 · повернено', 'v2 · 22.07.2026 · поточна', 'hash 59bd…0ce4 · manifest 428 рядків']],
  }

  if (decision) return <div className="external-page"><header><Brand/><span>Захищений перегляд</span></header><main className="external-receipt"><span className={`success-mark ${decision === 'accepted' ? 'synced' : ''}`}>{decision === 'accepted' ? <Check size={38}/> : <RotateCcw size={35}/>}</span><small>REVIEW RECEIPT · EXT-2026-044</small><h1>{decision === 'accepted' ? 'Операційно погоджено' : 'Повернено на уточнення'}</h1><p>{decision === 'accepted' ? 'Рішення стосується лише AVR-2026-06 · v2 і не є КЕП. Відправник отримав незмінний запис.' : 'Зафіксовано причину «уточнити обсяг EL-11.08». Відправник створить нову версію.'}</p><div className="access-summary"><span>Версія<b>v2 · 59bd…0ce4</b></span><span>Час<b>22.07.2026 · 11:24</b></span><span>Рівень<b>Authenticated workflow</b></span></div><button className="button button--dark" onClick={() => { setDecision(null); setStep(1) }}>Повернутися до пакета</button></main></div>

  return <div className="external-page"><header><Brand/><span>Захищений перегляд</span></header>{step === 0 ? <main className="external-entry"><span className="auth-lock"><LockKeyhole size={20}/></span><small>ЕнергоПро Монтаж запросила перегляд</small><h1>Пакет AVR-2026-06 · v2</h1><p>БЦ Horizon · Червень 2026 · посилання діє до 29.07.2026</p><label>Ваше ім’я<input defaultValue="Олександр Мельник"/></label><label>Компанія<input defaultValue="Horizon Development"/></label><label className="otp-field">Код з повідомлення<input defaultValue="581 204" inputMode="numeric"/></label><div className="privacy-line"><ShieldCheck size={18}/> Сесія обмежена цією версією. Завантаження вимкнено.</div><button className="button button--dark button--full" onClick={() => setStep(1)}>Відкрити пакет <ArrowRight size={17}/></button></main> : <main className="external-review"><section className="external-summary"><span className="package-icon package-icon--ready"><FileCheck2 size={23}/></span><div><small>AVR-2026-06 · VERSION 2</small><h1>2 650 000 ₴</h1><p>428 позицій · 84 докази · 1 розкритий waiver</p></div><span className="secure-version"><ShieldCheck size={17}/> hash 59bd…0ce4</span></section><section className="external-grid"><aside><span>РОЗДІЛИ</span>{sections.map(item => <button className={section === item ? 'active' : ''} aria-current={section === item ? 'page' : undefined} onClick={() => setSection(item)} key={item}>{item}{item === 'Waivers' && <b>1</b>}</button>)}</aside><article className="external-document"><header><span>ПЕРЕВІРКА ПЕРЕД РІШЕННЯМ · {section}</span><h2>{sectionCopy[section][0]}</h2></header><div className="external-money"><p><span>Заявлено</span><b>2 650 000 ₴</b></p><p><span>Без waiver</span><b>2 552 000 ₴</b></p></div><div className="external-warning"><AlertTriangle size={19}/><div><b>EL-11.08 · виконавча схема</b><p>Тимчасовий waiver до 31.07.2026. Документ очікується від замовника.</p></div></div><h3>{section}</h3>{sectionCopy[section][1].map(item => <p className="external-line" key={item}><Check size={15}/>{item}</p>)}</article><aside className="external-decision"><span>ВАШЕ РІШЕННЯ</span><h3>Лише для версії v2</h3><label>Причина повернення<select defaultValue="quantity"><option value="quantity">Уточнити обсяг EL-11.08</option><option value="waiver">Не приймаємо waiver</option><option value="document">Потрібен документ</option></select></label><button className="button button--outline button--full" onClick={() => setDecision('returned')}><RotateCcw size={16}/> Повернути</button><button className="button button--signal button--full" onClick={() => setDecision('accepted')}><Check size={17}/> Операційно погодити</button><small>Це authenticated workflow record, не кваліфікований електронний підпис.</small></aside></section></main>}</div>
}
