import { useState } from 'react'
import { Check, KeyRound, MapPin, Plus, ShieldCheck, UserRoundPlus } from 'lucide-react'
import AppShell from '../components/AppShell'
import Status from '../components/Status'
import useDialogA11y from '../components/useDialogA11y'

const members = [
  ['Ірина Коваленко','Керівниця ВТВ','Усі об’єкти','MFA','ready'],
  ['Максим Литвин','Керівник проєкту','БЦ Horizon','MFA','ready'],
  ['Сергій Коваль','Виконроб','БЦ Horizon · Секція B','Активний','blue'],
  ['Олена Шевчук','Польова фіксація','БЦ Horizon · Секція A','Активна','blue'],
  ['Наталія Бондар','Проєктна бухгалтерія','2 об’єкти','MFA','ready'],
]

export default function Team() {
  const [open, setOpen] = useState(false)
  const [sent, setSent] = useState(false)
  const [offboardingPhase, setOffboardingPhase] = useState('idle')
  const [exportedReview, setExportedReview] = useState(false)
  const [managed, setManaged] = useState(null)
  const dialogRef = useDialogA11y(open, () => setOpen(false))

  return <AppShell title="Команда й доступ" eyebrow="ЕнергоПро Монтаж" action={<button className="button button--dark button--small" onClick={() => { setOpen(true); setSent(false) }}><Plus size={16}/> Запросити</button>}>
    <div className="page-content team-page"><section className="access-health"><div><ShieldCheck size={23}/><span><b>Привілейовані ролі захищені MFA</b><small>Останній access review: 01.07.2026 · наступний 01.10.2026</small></span></div><span className="toolbar-updated">{exportedReview && <span className="toolbar-receipt">ACC-REV-260723 · CSV готово</span>} <button className="button button--outline button--small" onClick={() => setExportedReview(true)}>Експорт перевірки</button></span></section><section className="member-table"><header><span>Людина</span><span>Роль</span><span>Межі доступу</span><span>Безпека</span><span/></header>{members.map(([name, role, scope, security, tone]) => <article key={name}><div><span>{name.split(' ').map(item => item[0]).join('')}</span><b>{name}</b></div><strong>{role}</strong><span><MapPin size={14}/>{scope}</span><Status tone={tone}>{security}</Status><button className="quiet-button" aria-expanded={name !== 'Сергій Коваль' && managed === name} onClick={() => name === 'Сергій Коваль' ? setOffboardingPhase('planning') : setManaged(current => current === name ? null : name)}>{name === 'Сергій Коваль' ? 'Offboard' : 'Керувати'}</button></article>)}</section>
      {managed && <section className="panel offboarding-panel" aria-live="polite"><header><div><small>КЕРУВАННЯ УЧАСНИКОМ · {managed}</small><h3>{members.find(([name]) => name === managed)?.[1]} · {members.find(([name]) => name === managed)?.[2]}</h3></div><b className="published-pill">{members.find(([name]) => name === managed)?.[3]}</b></header><p><span>Зміна ролі або меж</span><b>exact-version команда з preview наслідків</b></p><p><span>Organization-wide offboarding</span><b>staged plan → fresh preview → atomic revoke (демо-сценарій показано для Сергія Коваля)</b></p><button className="button button--outline button--small" onClick={() => setManaged(null)}>Закрити</button></section>}
      {offboardingPhase !== 'idle' && <section className="panel offboarding-panel" aria-live="polite"><header><div><small>ORGANIZATION-WIDE OFFBOARDING · Сергій Коваль · membership v7</small><h3>{offboardingPhase === 'planning' ? 'Закрийте відповідальності в усіх проєктах' : offboardingPhase === 'preview' ? 'Fresh preview готовий до atomic revoke' : 'Учасника відкликано без orphan resources'}</h3></div><b className={offboardingPhase === 'done' ? 'published-pill' : 'draft-pill'}>{offboardingPhase === 'done' ? 'REVOKED' : 'NO REVOKE YET'}</b></header>{offboardingPhase === 'planning' && <><p><span>БЦ Horizon · ASN-741 · assignment v5</span><b>→ Максим · offline: manager review</b></p><p><span>ЖК River · RVW-2207-95 · review v4</span><b>→ Ірина Коваленко</b></p><p><span>ЖК River · correction + integration owner</span><b>→ Ірина · transfer ownership</b></p><button className="button button--dark button--small preview-offboarding" onClick={() => setOffboardingPhase('preview')}>Створити organization-wide preview</button></>}{offboardingPhase === 'preview' && <><p><span>Preview OFB-2407-09 · 2 projects · dependency hash</span><b>91d4…c820</b></p><p><span>Commit</span><b>4 resource resolutions + lease/session revoke + audit</b></p><button className="button button--signal button--small confirm-offboarding" onClick={() => setOffboardingPhase('done')}>Підтвердити atomic revoke</button></>}{offboardingPhase === 'done' && <div className="inline-receipt offboarding-receipt"><Check size={18}/><span><b>OFB-2407-10 · membership v8</b><small>2 projects закрито; assignments, reviews, corrections та ownership перенесено; leases/sessions недійсні</small></span></div>}</section>}
      <div className="domain-boundary"><KeyRound size={19}/><div><b>Support AktFlow не входить до цієї команди</b><span>Тимчасовий доступ потребує окремого grant, строку та видимого аудиту.</span></div></div></div>
    {open && <div className="modal-layer"><button className="drawer__backdrop" onClick={() => setOpen(false)} aria-label="Закрити"/><section ref={dialogRef} className="invite-dialog" role="dialog" aria-modal="true" aria-labelledby="invite-dialog-title">{sent ? <div className="payment-recorded" aria-live="polite"><span className="success-mark synced"><Check size={36}/></span><h2 id="invite-dialog-title">Запрошення поставлено в чергу</h2><p>Роль і межі зафіксовано. Повторне надсилання відкличе попередній token.</p><button className="button button--dark button--full" onClick={() => setOpen(false)}>Готово</button></div> : <><span className="auth-lock"><UserRoundPlus size={20}/></span><h2 id="invite-dialog-title">Запросити з найменшим доступом</h2><label>Робочий email<input type="email" defaultValue="reviewer@energopro.ua"/></label><label>Роль<select defaultValue="reviewer"><option value="reviewer">Внутрішня перевірка</option><option value="worker">Польова фіксація</option><option value="pm">Керівник проєкту</option></select></label><label>Об’єкт<select defaultValue="horizon"><option value="horizon">БЦ Horizon</option></select></label><label>Локації<select defaultValue="section-b"><option value="section-b">Лише Секція B</option><option value="all">Усі локації об’єкта</option></select></label><div className="role-preview"><b>Зможе:</b><span>переглядати й вирішувати evidence у Секції B</span><b>Не зможе:</b><span>бачити інші об’єкти, змінювати договір або тариф</span></div><button className="button button--dark button--full" onClick={() => setSent(true)}>Надіслати запрошення</button></>}</section></div>}
  </AppShell>
}
