import { useState } from 'react'
import { AlertTriangle, ArrowRight, Check, FilePlus2, Plus, Send, X } from 'lucide-react'
import AppShell from '../components/AppShell'
import Status from '../components/Status'
import useDialogA11y from '../components/useDialogA11y'

const seed = [
  { ref: 'VAR-024', title: 'Додатковий кабельний маршрут до серверної', amount: '286 400 ₴', state: 'Очікує підтвердження', tone: 'review', version: 'v2 · надіслано 3 дні тому' },
  { ref: 'VAR-021', title: 'Перенесення щита ЩР-12', amount: '94 800 ₴', state: 'Погоджено', tone: 'ready', version: 'v3 · включено до договору' },
  { ref: 'VAR-019', title: 'Тимчасове живлення секції B', amount: '128 000 ₴', state: 'Спір', tone: 'risk', version: 'v1 · коментар замовника' },
]

export default function Variations() {
  const [open, setOpen] = useState(false)
  const [step, setStep] = useState(0)
  const [issued, setIssued] = useState(false)
  const [detail, setDetail] = useState(null)
  const composerRef = useDialogA11y(open, () => setOpen(false))
  const detailRef = useDialogA11y(Boolean(detail), () => setDetail(null))

  return <AppShell title="Додаткові роботи" eyebrow="БЦ Horizon" action={<button className="button button--dark button--small" onClick={() => { setOpen(true); setStep(0); setIssued(false) }}><Plus size={16}/> Нова варіація</button>}>
    <div className="page-content variations-page"><section className="variation-summary"><div><span>У роботі</span><strong>414 400 ₴</strong><small>2 notices</small></div><div><span>Погоджено</span><strong>94 800 ₴</strong><small>1 включено до договору</small></div><div><span>Під ризиком</span><strong>128 000 ₴</strong><small>потрібна відповідь сьогодні</small></div></section><section className="variation-list"><header><span>Посилання</span><span>Опис і версія</span><span>Сума</span><span>Стан</span><span/></header>{seed.map(item => <article key={item.ref}><b>{item.ref}</b><div><strong>{item.title}</strong><small>{item.version}</small></div><strong>{item.amount}</strong><Status tone={item.tone}>{item.state}</Status><button className="button button--outline button--small" onClick={() => setDetail(item)}>Відкрити</button></article>)}</section></div>
    {detail && <div className="modal-layer"><button className="drawer__backdrop" onClick={() => setDetail(null)} aria-label="Закрити варіацію"/><section ref={detailRef} className="invite-dialog" role="dialog" aria-modal="true" aria-labelledby="variation-detail-title"><header style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}><div><small>{detail.ref} · {detail.version}</small><h2 id="variation-detail-title">{detail.title}</h2></div><button className="icon-button" onClick={() => setDetail(null)} aria-label="Закрити варіацію"><X size={18}/></button></header><div className="role-preview"><b>Сума:</b><span>{detail.amount}</span><b>Стан:</b><span>{detail.state}</span></div><p>Кожна версія variation незмінна: докази, сума й адресат зафіксовані в manifest. Нове рішення чи зміна обсягу створює наступну версію, а не редагує цю.</p><button className="button button--dark button--full" onClick={() => setDetail(null)}>Закрити</button></section></div>}
    {open && <div className="modal-layer"><button className="drawer__backdrop" onClick={() => setOpen(false)} aria-label="Закрити варіацію"/><section ref={composerRef} className="variation-composer" role="dialog" aria-modal="true" aria-labelledby="variation-dialog-title"><header><div><small>НОВА ВАРІАЦІЯ · КРОК {Math.min(step + 1, 3)} З 3</small><h2 id="variation-dialog-title">{issued ? 'Notice зафіксовано' : step === 0 ? 'Опишіть зміну' : step === 1 ? 'Докази та оцінка' : 'Перевірте версію перед видачею'}</h2></div><button className="icon-button" onClick={() => setOpen(false)} aria-label="Закрити варіацію"><X size={18}/></button></header>{issued ? <div className="issued-state"><span className="success-mark synced"><Check size={36}/></span><h3>VAR-025 · версія 1</h3><p>Зафіксовано точну версію, суму й докази. Це operational notice, а не КЕП чи погодження вартості.</p><div className="pilot-receipt"><Send size={19}/><div><small>НАСТУПНИЙ КРОК</small><b>Людина перевіряє адресата й надсилає notice поза AktFlow</b></div></div><button className="button button--dark button--full" onClick={() => setOpen(false)}>До реєстру</button></div> : <>
      <div className="composer-body">{step === 0 ? <><label>Назва<input defaultValue="Додаткове заземлення обладнання серверної"/></label><label>Локація<select defaultValue="server"><option value="server">Секція B · серверна</option></select></label><label>Що змінилось<textarea defaultValue="Замовник попросив додати окремий контур заземлення після погодження обладнання."/></label><label className="started-warning"><input type="checkbox" defaultChecked/><span><AlertTriangle size={18}/><b>Роботи вже розпочато без письмового підтвердження</b><small>AktFlow збере дату, причину та доступні докази.</small></span></label></> : step === 1 ? <><div className="attachment-drop"><FilePlus2 size={25}/><b>3 фото та лист завдання додано</b><span>Оригінали збережені; у notice піде індекс доказів.</span></div><div className="field-pair"><label>Матеріали<input defaultValue="74 000 ₴"/></label><label>Роботи<input defaultValue="42 800 ₴"/></label></div><label>Обґрунтування вартості<textarea defaultValue="Кабель заземлення, лоток, кріплення та 32 люд.-год."/></label></> : <><div className="variation-preview"><span>VAR-025 · v1</span><h3>Додаткове заземлення обладнання серверної</h3><p>Секція B · серверна</p><strong>116 800 ₴</strong><div><Check size={16}/> 4 докази у versioned manifest</div><div><Check size={16}/> Відмічено початок без письмового direction</div></div><p className="assurance-note"><AlertTriangle size={17}/> Кнопка нижче фіксує notice у AktFlow. Вона не надсилає лист і не створює КЕП.</p></>}</div>
      <footer>{step > 0 && <button className="button button--outline" onClick={() => setStep(step - 1)}>Назад</button>}<button className="button button--dark" onClick={() => step < 2 ? setStep(step + 1) : setIssued(true)}>{step < 2 ? <>Продовжити <ArrowRight size={17}/></> : <>Зафіксувати notice <Send size={16}/></>}</button></footer>
    </>}</section></div>}
  </AppShell>
}
