// GENERATED OUT OF technical/requirements/dbn-a31-5-2016-dodatok-v.csv AND
// COMPARED BACK AGAINST IT BYTE FOR BYTE by dodatok-v-fidelity.test.ts.
//
// Do not hand-edit a caption here. The captions are the state standard's own
// text — mixed apostrophes (U+0027 in «обов'язковий», U+2019 in «ім’я»),
// `посада,номер` without its space in one line and `посада, номер` with it two
// lines below, and trailing spaces the PDF's text layer carries. Every one of
// those is load-bearing under hidden-works-content-rules.md prohibition F, and
// a formatter that "fixes" them changes a regulatory document.
//
// Editing the wording here without editing the CSV is a content change under
// §"Change control", not a code change, whatever it looks like in a diff.
import type { FormFieldDefinition } from "./statutory-act-form";

const SOURCE = "ДБН А.3.1-5:2016, Додаток В (обов'язковий), с. 33-34; офіційний файл sha256=4592edafaa8097d3b9305b7934d080256d649616a2741b6a5537a28606a665e3; чинність редакції підтверджена власником 2026-08-10";

export const DODATOK_V_FIELDS: readonly FormFieldDefinition[] = [
  {
    fieldId: "v.В1.1",
    ordinal: 1,
    section: "В.1",
    caption: "ДОДАТОК В ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.2",
    ordinal: 2,
    section: "В.1",
    caption: "(обов'язковий) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.3",
    ordinal: 3,
    section: "В.1",
    caption: "ФОРМИ СТОРІНОК АКТА НА ЗАКРИТТЯ ПРИХОВАНИХ РОБІТ ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.4",
    ordinal: 4,
    section: "В.1",
    caption: "В.1 Форма першої сторінки ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.5",
    ordinal: 5,
    section: "В.1",
    caption: "АКТ НА ЗАКРИТТЯ ПРИХОВАНИХ РОБІТ ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.6",
    ordinal: 6,
    section: "В.1",
    caption: "_________________________________________________________________________________________ ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.7",
    ordinal: 7,
    section: "В.1",
    caption: "(найменування робіт) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.8",
    ordinal: 8,
    section: "В.1",
    caption: "виконаних в ________________________________________________________________________________  ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.9",
    ordinal: 9,
    section: "В.1",
    caption: "(найменування і місце розташування об'єкта будівництва) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.10",
    ordinal: 10,
    section: "В.1",
    caption: "\"____\"____________20___ р. ",
    binding: { kind: "recorded_fact", fact: "act_date" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.11",
    ordinal: 11,
    section: "В.1",
    caption: "Представник будівельної організації ____________________________________________________________  ",
    binding: { kind: "signatory", slot: "builder" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.12",
    ordinal: 12,
    section: "В.1",
    caption: "(прізвище, ініціали, посада) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.13",
    ordinal: 13,
    section: "В.1",
    caption: "_____________________________________________________________________________________________________ ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.14",
    ordinal: 14,
    section: "В.1",
    caption: "Представник технічного нагляду замовника ______________________________________________________  ",
    binding: { kind: "signatory", slot: "technical_supervision" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.15",
    ordinal: 15,
    section: "В.1",
    caption: "(прізвище, ініціали, посада,номер та серія сертифіката) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.16",
    ordinal: 16,
    section: "В.1",
    caption: "Представник проектної організації (згідно з договором про здійснення авторського нагляду) ",
    binding: { kind: "signatory", slot: "designer_supervision" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.17",
    ordinal: 17,
    section: "В.1",
    caption: "______________________________________________________________________________________ ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.18",
    ordinal: 18,
    section: "В.1",
    caption: "(прізвище, ініціали, посада, номер та серія сертифіката) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.19",
    ordinal: 19,
    section: "В.1",
    caption: "провели огляд робіт, виконаних _______________________________________________________________  ",
    binding: { kind: "recorded_fact", fact: "builder_organisation_name" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.20",
    ordinal: 20,
    section: "В.1",
    caption: "(найменування будівельної організації) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.21",
    ordinal: 21,
    section: "В.1",
    caption: "і склали цей акт про наступне: ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.22",
    ordinal: 22,
    section: "В.1",
    caption: "1. До закриття пред'явлені такі роботи: _____________________________________________________  ",
    binding: { kind: "quantity_lines" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.23",
    ordinal: 23,
    section: "В.1",
    caption: "(найменування прихованих робіт) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.24",
    ordinal: 24,
    section: "В.1",
    caption: "2. Роботи виконані за проектною документацією  ____________________________________________  ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.25",
    ordinal: 25,
    section: "В.1",
    caption: "(найменування проектної організації, номер креслень і дата їх складання) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.26",
    ordinal: 26,
    section: "В.1",
    caption: "3. При виконанні робіт застосовані ________________________________________________________  ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.27",
    ordinal: 27,
    section: "В.1",
    caption: "(найменування матеріалів, конструкцій з посиланням на сертифікати або інші документи) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.28",
    ordinal: 28,
    section: "В.1",
    caption: "4. При виконанні робіт відсутні (або допущені) відхилення від проектної документації ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.29",
    ordinal: 29,
    section: "В.1",
    caption: "(за наявності відхилень вказується, з ким і як погоджені, номер креслень і дата погодження) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.30",
    ordinal: 30,
    section: "В.1",
    caption: "5. Дата: початку робіт  ___________________________________  ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В1.31",
    ordinal: 31,
    section: "В.1",
    caption: "закінчення робіт _________________________________  ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.32",
    ordinal: 32,
    section: "В.2",
    caption: "В.2 Форма останньої сторінки ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.33",
    ordinal: 33,
    section: "В.2",
    caption: "Рішення ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.34",
    ordinal: 34,
    section: "В.2",
    caption: "Роботи виконані відповідно до проектної документації, стандартів, будівельних норм і правил, технічних ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.35",
    ordinal: 35,
    section: "В.2",
    caption: "умов і відповідають вимогам їх прийняття. ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.36",
    ordinal: 36,
    section: "В.2",
    caption: "На основі викладеного дозволяється виконання наступних робіт ",
    binding: { kind: "decision_blocks" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.37",
    ordinal: 37,
    section: "В.2",
    caption: "____________________________________________________________________________________________ ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.38",
    ordinal: 38,
    section: "В.2",
    caption: "____________________________________________________________________________________________ ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.39",
    ordinal: 39,
    section: "В.2",
    caption: "(найменування робіт і конструкцій) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.40",
    ordinal: 40,
    section: "В.2",
    caption: "Представник будівельної організації ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.41",
    ordinal: 41,
    section: "В.2",
    caption: "Представник технічного нагляду ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.42",
    ordinal: 42,
    section: "В.2",
    caption: "замовника ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.43",
    ordinal: 43,
    section: "В.2",
    caption: "Представник проектної організації ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.44",
    ordinal: 44,
    section: "В.2",
    caption: "(підпис) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.45",
    ordinal: 45,
    section: "В.2",
    caption: "(Прізвище, ім’я, по батькові) ",
    binding: { kind: "signatory", slot: "builder" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.46",
    ordinal: 46,
    section: "В.2",
    caption: "(підпис) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.47",
    ordinal: 47,
    section: "В.2",
    caption: "(Прізвище, ім’я, по батькові) ",
    binding: { kind: "signatory", slot: "technical_supervision" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.48",
    ordinal: 48,
    section: "В.2",
    caption: "(підпис) ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.49",
    ordinal: 49,
    section: "В.2",
    caption: "(Прізвище, ім’я, по батькові) ",
    binding: { kind: "signatory", slot: "designer_supervision" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.50",
    ordinal: 50,
    section: "В.2",
    caption: "Примітка. Керівник генпідрядної організації не пізніше ніж за 5 робочих днів інформує учасників про дату і ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
  {
    fieldId: "v.В2.51",
    ordinal: 51,
    section: "В.2",
    caption: "місце проведення роботи. ",
    binding: { kind: "static" },
    verification: "VERIFIED_PRIMARY",
    source: SOURCE,
  },
];
