// Static image imports (`import photo from "../../public/images/photo-tray-thumb.jpg"`)
// take their types from Next's image-types module. `next-env.d.ts` references it
// too, but that file is generated by `next build`/`next dev` and git-ignored, and
// CI runs `tsc --noEmit` before any build — so the reference has to live in a
// tracked file as well. Keep this in sync with what next-env.d.ts emits.
/// <reference types="next/image-types/global" />
