#!/usr/bin/env python3
"""Render project-owned Agency profiles offline. Requires Python 3.11+.

Canonical sources live in agents/ (registry.json, the family's common protocol
and roles/<name>.md). Host files are generated from them:
.claude/agents/<name>.md for Claude Code and .codex/agents/<name>.toml for Codex.
Run with --write to regenerate and --check to fail on drift (CI runs --check).
Ported from the deploy-doc project's generator; the one addition is the
optional per-role `codex_sandbox_mode`, see render().
"""
import argparse
import json
from pathlib import Path
import re
import sys
import tomllib

ROOT = Path(__file__).resolve().parents[1]
MARKER = "Generated by scripts/sync-agents.py; edit agents/ sources instead."
ALLOWED_TOOLS = {"Read", "Grep", "Glob", "Bash", "Edit", "Write", "WebSearch", "WebFetch"}
ROLE_KEYS = {"name", "family", "description", "profile", "access", "claude_tools", "codex_sandbox_mode"}
READ_SANDBOXES = {"read-only", "workspace-write"}


def load_families(registry):
    """A family is one development area's role set: a name prefix, its own
    common protocol, and exactly one implementer allowed write intent."""
    families = {}
    for family in registry.get("families", []):
        prefix = family.get("prefix", "")
        if not re.fullmatch(r"[a-z]+", prefix) or prefix in families:
            raise ValueError(f"Invalid or duplicate family prefix: {prefix!r}")
        if not str(family.get("area", "")).strip():
            raise ValueError(f"Family has no area: {prefix}")
        common = family.get("common", "")
        common_path = ROOT / common
        if not re.fullmatch(r"agents/[A-Za-z0-9._-]+\.md", common) or common_path.is_symlink():
            raise ValueError(f"Common protocol must be a local agents/*.md file: {prefix}")
        if not family.get("implementer", "").startswith(prefix + "-"):
            raise ValueError(f"Implementer must belong to its own family: {prefix}")
        families[prefix] = {**family, "common_text": common_path.read_text().strip()}
    if not families:
        raise ValueError("Registry defines no role families")
    return families


def codex_sandbox(role, name):
    """Codex sandbox for a role. A write role inherits the host's sandbox, as
    upstream Codex does when sandbox_mode is omitted. A read role defaults to
    read-only; only a QA role may ask for workspace-write, because verification
    runs test suites that write caches and connect to the local database, and a
    read-only sandbox would turn every such check into NOT RUN."""
    requested = role.get("codex_sandbox_mode")
    if role["access"] == "write":
        if requested is not None:
            raise ValueError(f"A write role inherits the host sandbox; remove codex_sandbox_mode: {name}")
        return None
    sandbox = requested or "read-only"
    if sandbox not in READ_SANDBOXES:
        raise ValueError(f"Invalid codex_sandbox_mode {sandbox!r}: {name}")
    if sandbox == "workspace-write" and not name.endswith("-qa"):
        raise ValueError(f"Only a *-qa role may use workspace-write: {name}")
    return sandbox


def render():
    registry = json.loads((ROOT / "agents/registry.json").read_text())
    if registry["schema_version"] != 2:
        raise ValueError("Unsupported registry schema")
    families = load_families(registry)
    outputs, names, profiles = {}, set(), set()
    counts = {prefix: 0 for prefix in families}
    for role in registry["roles"]:
        name = role["name"]
        unknown = set(role) - ROLE_KEYS
        if unknown:
            raise ValueError(f"Unknown registry keys for {name}: {', '.join(sorted(unknown))}")
        family = families.get(role.get("family"))
        if family is None:
            raise ValueError(f"Unknown family for role: {name}")
        prefix = family["prefix"]
        if not re.fullmatch(rf"{prefix}-[a-z][a-z-]*", name) or name in names:
            raise ValueError(f"Invalid or duplicate role: {name}")
        names.add(name)
        counts[prefix] += 1
        expected = f"agents/roles/{name}.md"
        if role["profile"] != expected or role["access"] not in {"read", "write"}:
            raise ValueError(f"Invalid role scope: {name}")
        if role["access"] == "write" and name != family["implementer"]:
            raise ValueError(
                f"Only {family['implementer']} may have write intent in the {prefix} family"
            )
        profile = ROOT / expected
        if profile.is_symlink():
            raise ValueError(f"Profile must be a local file: {profile}")
        profiles.add(profile)
        body = family["common_text"] + "\n\n" + profile.read_text().strip() + "\n"
        description = role["description"]
        # isprintable() also rejects newlines, C0/C1 controls, U+2028 and U+FEFF:
        # json.dumps leaves the last three unescaped, and YAML frontmatter would
        # reject or reinterpret them while the TOML round trip still passed.
        if not description.strip() or not description.isprintable():
            raise ValueError(f"Invalid description: {name}")
        fields = {"name": name, "description": description}
        sandbox = codex_sandbox(role, name)
        if sandbox is not None:
            fields["sandbox_mode"] = sandbox
        fields["developer_instructions"] = body
        toml = "# " + MARKER + "\n" + "\n".join(
            f"{key} = {json.dumps(value, ensure_ascii=False)}"
            for key, value in fields.items()
        ) + "\n"
        if tomllib.loads(toml) != fields:
            raise ValueError(f"TOML round trip failed: {name}")
        tools = role["claude_tools"]
        toolset = set(tools.split(", "))
        if not toolset <= ALLOWED_TOOLS or not {"Read", "Grep", "Glob"} <= toolset:
            raise ValueError(f"Invalid Claude tools: {name}")
        if role["access"] == "read" and toolset & {"Edit", "Write"}:
            raise ValueError(f"Unexpected edit tools: {name}")
        claude = (
            "---\n"
            f"name: {json.dumps(name)}\n"
            f"description: {json.dumps(description, ensure_ascii=False)}\n"
            f"tools: {tools}\n"
            "---\n\n"
            f"<!-- {MARKER} -->\n\n" + body
        )
        outputs[ROOT / f".codex/agents/{name}.toml"] = toml
        outputs[ROOT / f".claude/agents/{name}.md"] = claude
    if not names:
        raise ValueError("Empty registry")
    empty = [prefix for prefix, count in counts.items() if count == 0]
    if empty:
        raise ValueError(f"Families without roles: {', '.join(empty)}")
    for family in families.values():
        if family["implementer"] not in names:
            raise ValueError(f"Implementer is not a registered role: {family['implementer']}")
    if profiles != set((ROOT / "agents/roles").glob("*.md")):
        raise ValueError("Unregistered or missing canonical profiles")
    return outputs, counts


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="Regenerate project-owned host files")
    mode.add_argument("--check", action="store_true", help="Check syntax and generation drift without writes")
    args = parser.parse_args()
    outputs, counts = render()
    owned_prefixes = tuple(f"{prefix}-" for prefix in counts)
    problems = []
    # Refuse collisions before changing any files. Never remove stale profiles.
    for folder, suffix in ((".codex/agents", ".toml"), (".claude/agents", ".md")):
        directory = ROOT / folder
        if directory.is_symlink() or directory.parent.is_symlink():
            raise ValueError(f"Output directory must be local: {folder}")
        for path in directory.glob("*" + suffix):
            if path.is_symlink():
                raise ValueError(f"Refusing symlink: {path}")
            content = path.read_text()
            if path not in outputs and (path.name.startswith(owned_prefixes) or MARKER in content):
                problems.append(f"Stale/colliding profile: {path.relative_to(ROOT)}")
            elif path in outputs and MARKER not in content:
                problems.append(f"Refusing to overwrite unowned file: {path.relative_to(ROOT)}")
    if problems:
        raise ValueError("\n".join(problems))
    for path, expected in outputs.items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected)
        elif not path.exists() or path.read_text() != expected:
            problems.append(f"Missing or drifted: {path.relative_to(ROOT)}")
    if problems:
        raise ValueError("\n".join(problems))
    verb = "Generated" if args.write else "Verified"
    summary = ", ".join(f"{prefix}: {count}" for prefix, count in counts.items())
    print(f"{verb} {len(outputs)} host profiles from {len(outputs) // 2} canonical roles ({summary}).")


if __name__ == "__main__":
    if sys.version_info < (3, 11):
        print("scripts/sync-agents.py requires Python 3.11+ (tomllib)", file=sys.stderr)
        sys.exit(1)
    try:
        main()
    except (ValueError, KeyError, OSError) as exc:
        print(str(exc), file=sys.stderr)
        sys.exit(1)
